version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/nest/
      - /nest/node_modules
    command: yarn server:dev
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: front
    ports:
      - "4200:4200"
    volumes:
      - ./client:/react/
      - /react/node_modules
    links:
      - "backend"
    command: yarn dev
